variable "db_name" {
  description = "Logical database name to create on the shared instance (e.g. \"commerce\")."
  type        = string
}

variable "db_owner" {
  description = "Owner role name. Created with login; owns the database; password is generated by the module."
  type        = string
}

variable "db_schemas" {
  description = "Schemas to grant ALL privileges on to the owner role."
  type        = list(string)
  default     = ["public"]
}

variable "secret_name" {
  description = "AWS Secrets Manager secret name for the generated app credentials (e.g. \"/commerce-api/rds/psql\")."
  type        = string
}

# Used only to encode connection info into the AWS Secrets Manager secret —
# NOT used to configure the postgresql provider (that happens at the caller).
variable "rds_host" {
  description = "Hostname of the shared RDS instance (for the secret payload)."
  type        = string
}

variable "database_port" {
  description = "Port of the shared RDS instance (for the secret payload)."
  type        = number
  default     = 5432
}
